#!/usr/bin/env python

import sys
import os
import csv
import statistics
import tabulate

if len(sys.argv) < 3:
    print('Usage: coeffs <file> <interval>')
    sys.exit(1)

cwd = os.getcwd()
path = os.path.join(cwd, sys.argv[1])
if not os.path.isfile(path):
    print('File "' + path + '" does not exist.')
    sys.exit(1)

try:
    interval = int(sys.argv[2])
except ValueError:
    print('"' + sys.argv[2] + '" is not an integer')
    sys.exit(1)
if interval <= 2:
    print('Interval is <= 2')
    sys.exit(1)

# # # # # # # # #
# Main program #
# # # # # # # #

cd = []
cl = []
with open(path) as f:
    # Skip header
    for i in range(0, 9):
        f.readline()
    reader = csv.reader(f, delimiter='\t')
    for row in reader:
        cd.append(float(row[2]))
        cl.append(float(row[3]))

assert len(cd) == len(cl)

if interval > len(cd):
    print('Too many steps: ' + str(interval) + ', maximum: ' + str(len(cd)))
    sys.exit(1)

headers = ['Interval', 'Cd mean', 'Cd stdev', 'Cl mean', 'Cl stdev']
table = []
for i in range(0, len(cd) - interval + 1, interval):
    cd_mean = statistics.mean(cd[i:i + interval])
    cd_stdev = statistics.stdev(cd[i:i + interval])
    cl_mean = statistics.mean(cl[i:i + interval])
    cl_stdev = statistics.stdev(cl[i:i + interval])
    table.append([
        str(i) + '-' + str(i + interval),
        round(cd_mean, 3), round(cd_stdev, 5),
        round(cl_mean, 3), round(cl_stdev, 5)
    ])
print(tabulate.tabulate(table, headers), '\n')

headers = ['', 'Mean', 'Stdev']
cd_mean = statistics.mean(cd[-interval:])
cd_stdev = statistics.stdev(cd[-interval:])
cl_mean = statistics.mean(cl[-interval:])
cl_stdev = statistics.stdev(cl[-interval:])
table = [['Cd', round(cd_mean, 3), round(cd_stdev, 5)],
         ['Cl', round(cl_mean, 3), round(cl_stdev, 5)]]
print('Last interval:')
print(tabulate.tabulate(table, headers))
